name: Branch Release

on:
  schedule:
    - cron: '0 6 * * 1-4' # Every Monday to Thursday at 6am UTC - 3am BRT

jobs:
  delete-branch-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Delete Git branch release
        run: |
          git branch -r --list '*/release/*' | sed 's/origin\///' | xargs -n 1 git push origin --delete

  create-branch-release:
    runs-on: ubuntu-latest
    needs: delete-branch-release

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Create Version
        uses: actions/github-script@v6
        id: create-version
        with:
          script: |
            const currentDate = new Date()
            const year = currentDate.getFullYear().toString().slice(2)
            const month = currentDate.getMonth()
            const date = currentDate.getDate()
            const version = year + '.' + month + '.' + date
            return version

      - name: Setup Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"

      - name: Create Git branch release
        run: |
          git checkout -b release/v${{ fromJSON(steps.create-version.outputs.result) }}
          git push origin release/v${{ fromJSON(steps.create-version.outputs.result) }}
