name: "PR: Jira Comments"

on:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - reopened

jobs:
  pull-request-open:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - run: npm install adf-builder

      - name: Get Jira Card
        uses: actions/github-script@v6
        id: GetJiraCard
        with:
         script: |
           const jira = require('./.github/workflows/jira.js');
           const prTitle = "${{ github.event.pull_request.title }}";
           return jira.createJiraCommentEndpoint(prTitle);

      - name: Create Jira Comments
        uses: actions/github-script@v6
        id: CreateJiraComment
        with:
         script: |
           const jira = require('./.github/workflows/jira.js');
           const prNumber = "${{ github.event.pull_request.number }}";
           return jira.pullRequestCreated(prNumber);

      - name: Call Jira API
        run: |
          curl \
            --request POST \
            --url ${{ steps.GetJiraCard.outputs.result }} \
            --user ${{ secrets.JIRA_USER }}:${{ secrets.JIRA_TOKEN }} \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --data '{ "body": ${{ steps.CreateJiraComment.outputs.result }} }'
