name: "PR: Jira Comments"

on:
  pull_request:
    branches:
      - main
      - releases/**
      - stage
    types:
      - opened

jobs:
  pr-open:
   runs-on: ubuntu-latest

   steps:
     - name: Jira Comments
       uses: actions/github-script@v6
       id: CreateBranchRelease
       with:
         script: |
           const hira = require('./.github/workflows/jira.js');
           return hira.pullRequestCreated();
