name: "PR: Title Regex"

on:
  pull_request:
    branches:
      - main
      - releases/**
      - stage

jobs:
  test-regex:
    runs-on: ubuntu-latest

    steps:
      - name: Test RegEx
        uses: actions/github-script@v6
        with:
          script: |
            const title = context.issue.title;

            const regexTasks = /^(bugfix|feat|hotfix|tech)\(CXM-?\d{0,4}\): .+$/;
            const regexRelease = /^release \| v\d+\.\d+\.\d+.+$/;

            if (regexTasks.test(title) === false && regexRelease.test(title) === false) {
              console.log(title);
              console.log("RegEx Tasks: " + regexTasks.test(title));
              console.log("RegEx Release: " + regexRelease.test(title));
              core.setFailed("Invalid PR title. Title should match the specified pattern.");
            }
