name: "PR: Jira Comments"

on:
  workflow_dispatch:

jobs:
  pull-request-open:
   runs-on: ubuntu-latest

   steps:
     - run: npm install adf-builder

     - name: Create Jira Comments
       uses: actions/github-script@v6
       id: CreateJiraComment
       with:
         script: |
           const jira = require('./.github/workflows/jira.js');
           return jira.pullRequestCreated();

     - name: Call Jira API
       run: |
         curl \
           --request POST \
           --url 'https://trackco.atlassian.net/rest/api/3/issue/CXM-4065/comment' \
           --user ${{ secrets.JIRA_USER }}:${{ secrets.JIRA_TOKEN }} \
           --header 'Accept: application/json' \
           --header 'Content-Type: application/json' \
           --data '{ "body": ${{ steps.CreateJiraComment.outputs.result }} }'
