name: "PR: Jira Comments"

on:
  workflow_dispatch:

jobs:
  pull-request-open:
   runs-on: ubuntu-latest

   steps:
#     - run: npm install adf-builder

     - name: Jira Comments
       uses: actions/github-script@v6
       with:
         script: |
           const jira = require('./.github/workflows/jira.js');
           jira.pullRequestCreated();
