name: Update Branch Stage

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  update-stage:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Create Version
        uses: actions/github-script@v6
        id: create-version
        with:
          script: |
            const currentDate = new Date()
            const year = currentDate.getFullYear().toString().slice(2)
            const month = currentDate.getMonth()
            const date = currentDate.getDate()
            const version = year + '.' + month + '.' + date
            return version

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const version = v${{ fromJSON(steps.create-version.outputs.result) }}
            const { repo, owner } = context.repo;

            core.debug(JSON.stringify(context, null, 2));
            core.debug(JSON.stringify(github, null, 2));

            const pullRequest = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: context.issue.number
            });

            const result = await github.rest.pulls.create({
              title: `release | v${version} | merge in stage`,
              owner,
              repo,
              head: 'main',
              base: 'stage',
              body: [
                pullRequest.data.body,
                '',
                '---',
                '',
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
