name: Update Branch Stage

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  update-stage:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Create Version
        uses: actions/github-script@v6
        id: create-version
        with:
          script: |
            const currentDate = new Date()
            const year = currentDate.getFullYear().toString().slice(2)
            const month = currentDate.getMonth() + 1
            const date = currentDate.getDate()
            const version = year + '.' + month + '.' + date
            return version

      - name: Create Pull Request
        uses: actions/github-script@v6
        id: create-pull-request
        with:
          script: |
            const { repo, owner } = context.repo;

            const pullRequest = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: context.issue.number
            });

            const result = await github.rest.pulls.create({
              title: 'release | v${{ fromJSON(steps.create-version.outputs.result) }} | merge in stage',
              owner,
              repo,
              head: 'main',
              base: 'stage',
              body: [
                pullRequest.data.body,
              ].join('\n')
            });

            return result;

      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ fromJSON(steps.create-pull-request.outputs.result) }}
          method: merge
          repo: jonathanbergson/poc-github-actions
