name: Update Branch Stage

on:
  pull_request:
    branches:
      - main

jobs:
  update-stage:
    runs-on: ubuntu-latest

    steps:
      - name: Create Version
        uses: actions/github-script@v6
        id: create-version
        with:
          script: |
            const currentDate = new Date()
            const year = currentDate.getFullYear().toString().slice(2)
            const month = currentDate.getMonth()
            const date = currentDate.getDate()
            const version = year + '.' + month + '.' + date
            return version

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const version = v${{ fromJSON(steps.create-version.outputs.result) }}
            const { repo, owner } = context.repo;
            console.log(github);
            const result = await github.rest.pulls.create({
              title: `release | v${version} | merge in stage`,
              owner,
              repo,
              head: 'main',
              base: 'stage',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
