name: Create Version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Create Version
        uses: actions/github-script@v6
        id: create-version
        with:
          script: |
            try {
              const currentDate = new Date()
              const year = currentDate.getFullYear().toString().slice(2)
              const month = currentDate.getMonth()
              const date = currentDate.getDate()
              const version = year + '.' + month + '.' + date
              return version
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Create Git tag
        run: |
          git tag -a v${{ fromJSON(steps.create-version.outputs.result) }} -m "New version v${{ fromJSON(steps.create-version.outputs.result) }}"
          git push origin :refs/tags/v${{ fromJSON(steps.create-version.outputs.result) }}
