name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Bolinha
        run: echo ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ env.GITHUB_TOKEN }}

      - name: Create Version
        uses: actions/github-script@v6
        id: create-version
        with:
          script: |
            const currentDate = new Date()
            const year = currentDate.getFullYear().toString().slice(2)
            const month = currentDate.getMonth() + 1
            const date = currentDate.getDate()
            const version = year + '.' + month + '.' + date
            return version

      - name: Setup Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"

      - name: Set Version
        run: npm version ${{ fromJSON(steps.create-version.outputs.result) }} --no-git-tag-version --allow-same-version

      - name: Push changes
        run: |
          git add package.json --ignore-errors
          git commit -m "ci(bump-version): v${{ fromJSON(steps.create-version.outputs.result) }}" --allow-empty
          git push origin main

      - name: Create Git tag
        run: |
          git tag -a v${{ fromJSON(steps.create-version.outputs.result) }} -m "New version v${{ fromJSON(steps.create-version.outputs.result) }}" -f
          git push -f --tags
